name: /hdd4/jiet/code/tree-of-thought-llm/env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohttp=3.8.3=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - async-timeout=4.0.2=py311h06a4308_0
  - attrs=22.1.0=py311h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py311hbed6279_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2023.5.7=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py311h06a4308_0
  - contourpy=1.0.5=py311hdb19cb5_0
  - cryptography=39.0.1=py311h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py311h06a4308_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py311h5eee18b_0
  - giflib=5.2.1=h5eee18b_3
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - joblib=1.2.0=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py311h6a678d5_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-base=3.7.1=py311ha02d727_1
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - multidict=6.0.2=py311h5eee18b_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.4=py311h65dcdc2_1
  - numpy=1.24.3=py311h08b1b3b_1
  - numpy-base=1.24.3=py311hf175353_1
  - openai=0.27.4=py311h06a4308_0
  - openpyxl=3.0.10=py311h5eee18b_0
  - openssl=1.1.1t=h7f8727e_0
  - pandas=1.5.3=py311hba01205_0
  - pandas-stubs=1.5.3.230203=py311h06a4308_0
  - pillow=9.4.0=py311h6a678d5_0
  - pip=23.0.1=py311h06a4308_0
  - plotly=5.9.0=py311h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.3=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.7=py311h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py311h06a4308_0
  - scikit-learn=1.2.2=py311h6a678d5_1
  - scipy=1.10.1=py311h08b1b3b_1
  - setuptools=67.8.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py311h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - types-pytz=2022.4.0.0=py311h06a4308_1
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py311h06a4308_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yarl=1.8.1=py311h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - backoff==2.2.1
      - cmake==3.26.4
      - comm==0.1.3
      - debugpy==1.6.7
      - decorator==5.1.1
      - executing==1.2.0
      - filelock==3.12.0
      - fsspec==2023.5.0
      - huggingface-hub==0.15.1
      - ipykernel==6.23.1
      - ipython==8.14.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - lit==16.0.5.post0
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.5.1
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - pyyaml==6.0
      - pyzmq==25.1.0
      - regex==2023.6.3
      - safetensors==0.3.1
      - stack-data==0.6.2
      - sympy==1.12
      - tokenizers==0.13.3
      - torch==2.0.1
      - tornado==6.3.2
      - traitlets==5.9.0
      - transformers==4.30.0
      - triton==2.0.0
      - typing-extensions==4.6.3
      - wcwidth==0.2.6
prefix: /hdd4/jiet/code/tree-of-thought-llm/env
